### ISSUE TITLE
..

### ISSUE THREAD

**Issue by Ray-0403** [EconomistGrant/HTFE-tensortrade#3]

**Comment by EconomistGrant** [comment]
是这样的。这个算法是基于之前某个项目的四个因子值进行因子的整合和进一步的挖掘。原数据是分钟级别的因子，然后重采样到60分钟频率。因为这个框架刚搭起来，用高信息度的因子去验证能否达到信息整合和进一步挖掘的效果，并没有考虑到数据归一化、调参等。

**Comment by Ray-0403** [comment]
> 是这样的。这个算法是基于之前某个项目的四个因子值进行因子的整合和进一步的挖掘。原数据是分钟级别的因子，然后重采样到60分钟频率。因为这个框架刚搭起来，用高信息度的因子去验证能否达到信息整合和进一步挖掘的效果，并没有考虑到数据归一化、调参等。

你好 请问是否可以分享一下这个框架后续的代码 我也有些ideas想整合进去试验一下
